### ISSUE TITLE
Change GoPro from fisheye lens

### ISSUE THREAD

**Issue by tianatonnu** [NGCP/VTOL#159]
The fisheye lens on the GoPro camera may be interfering with the CV algorithms.

Also look into removing GoPro UI stats from video stream if possible so that image cropping is not necessary.

**Comment by jkao97** [comment]
Just to document here / have a record:

https://www.veedyou.com/gopro-fisheye/

tldr: 
HERO4+ : use linear mode - completely eliminates fisheye
HERO3 and below: use medium / narrow view to reduce fisheye
