### ISSUE TITLE
Set altitude method for quad

### ISSUE THREAD

**Issue by nmcobb** [NGCP/VTOL#202]

**Comment by nmcobb** [comment]
Lets keep this open until you PR. I'm assuming you closed this because you finished?

**Comment by vincentvilo** [comment]
> Lets keep this open until you PR. I'm assuming you closed this because you finished?

Sorry, I think I accidentally clicked the close button. I'm working on a different issue, so I must have misclicked the button.

**Comment by nmcobb** [comment]
Gotcha no worries!
